---
- hosts: server
  vars:
    testbed_name: wilab
  tasks:
    - name: "Install MQTT Broker"
      become: True
      apt:
        name: mosquitto
        state: present

    #install node-red
    - name: "Install NodeJS and npm"
      become: True
      apt:
        name: npm
        state: present
    - name: "Install Node Red"
      become: True
      npm:
        name: node-red
        global: true

    - name: "Install Node Red Msg Speed"
      become: True
      npm:
        name: node-red-contrib-msg-speed
        global: true
    - name: "Install Node Red Dashboard"
      become: True
      npm:
        name: node-red-dashboard
        global: true
    - name: "Create nodered group"
      become: True
      group:
        name: nodered
    - name: "Create nodered user"
      become: True
      user:
        name: nodered
        group: nodered
        shell: /sbin/nologin

    - name: "Install Opentestbed Dashboard flows"
      become: True
      template:
        src: all_flows.json.j2
        dest: /home/nodered/all_flows.json
    - name: "Install nodered service"
      become: True
      copy:
        src: nodered.service
        dest: /etc/systemd/system/nodered.service

    - name: "Start nodered service"
      become: True
      systemd:
        name: nodered.service
        daemon_reload: yes
        state: restarted
        enabled: yes

    # Install nginx and forward traffic to :80 to /ui of nodered
    - name: Install NGINX
      become: True
      apt:
        name: nginx
        state: present
    - name: add nginx config file for otb ui
      become: True
      copy:
        src: nginx_otbui.cfg
        dest: /etc/nginx/sites-available/otbui
    - name: create symlink
      become: True
      file:
        src: /etc/nginx/sites-available/otbui
        dest: /etc/nginx/sites-enabled/default
        state: link
    - name: enable and restart nginx
      become: True
      service:
        name: nginx
        enabled: yes
        state: restarted
