- hosts: sensor
  tasks:

    - name: "Update AP Cache"
      become: True
      apt:
        update_cache: yes

    - name: "Install OpenTestbed dependencies"
      become: True
      apt:
        name: python3-pip

    - name: "Install yepkit dependencies"
      become: True
      apt:
        name: ykush-control
      when: ansible_distribution == 'Ubuntu' and ansible_lsb.major_release|int >= 18

    - name: "Install yepkit dependencies"
      become: True
      apt:
        name: libhidapi-libusb0
      when: ansible_distribution != "Ubuntu" or ansible_lsb.major_release|int < 18

    - name: "Add user to dialout group"
      become: True
      user:
        append: true
        groups: dialout
        name: "{{ ansible_user_id }}"

    - name: "Create opentestbed directory"
      become: True
      file:
        name: /opt/opentestbed
        state: directory
        owner: "{{ ansible_user_id }}"
    - name: "Get OpenTestbed code"
      git:
        repo: https://github.com/twalcari/opentestbed
        dest: /opt/opentestbed
    - name: "Install OpenTestbed"
      become: True
      pip:
        name: file:///opt/opentestbed
        editable: yes
        executable: pip3

    - name: "Install Supervisor"
      become: True
      apt:
        name: supervisor

    - name: "Derive broker address"
      command: hostname | cut -d'.' -f2- | sed 's/wilab1/wall2/'
      register: server_hostname_suffix

    - set_fact:
        broker_hostname: "server.{{ server_hostname_suffix.stdout }}"

    - name: "Add opentestbed program to supervisor"
      become: True
      template:
        src: sensor-supervisord.conf.j2
        dest: /etc/supervisor/conf.d/otbox.conf

    - name: "Restart supervisor"
      become: True
      systemd:
        name: supervisor
        state: restarted