- hosts: sensor
  tasks:

    - name: "Update APT Cache"
      become: True
      apt:
        update_cache: yes

    - name: "Install OpenTestbed dependencies"
      become: True
      apt:
        name: python-pip

    - name: "Install yepkit dependencies"
      become: True
      apt:
        name: ykush-control
      when: ansible_distribution == 'Ubuntu' and ansible_lsb.major_release|int >= 18

    - name: "Install yepkit dependencies"
      become: True
      apt:
        name: libhidapi-libusb0
      when: ansible_distribution != "Ubuntu" or ansible_lsb.major_release|int < 18

    - name: "Add user to dialout group"
      become: True
      user:
        append: true
        groups: dialout
        name: "{{ ansible_user_id }}"

    - name: "Create opentestbed directory"
      become: True
      file:
        name: /opt/opentestbed
        state: directory
        owner: "{{ ansible_user_id }}"

    - name: "Copy OpenTestbed bootloaders"
      copy:
        src: ../../bootloaders
        dest: /opt/opentestbed/

    - name: "Copy OpenTestbed install dir"
      copy:
        src: ../../install
        dest: /opt/opentestbed/

    - name: "Copy OpenTestbed script"
      copy:
        src: ../../otbox.py
        dest: /opt/opentestbed/

    - name: "Copy OpenTestbed cli"
      copy:
        src: ../../cli.py
        dest: /opt/opentestbed/

    - name: "Install OpenTestbed"
      become: True
      pip:
        requirements: /opt/opentestbed/install/requirements.txt
        executable: pip

    - name: "Install Supervisor"
      become: True
      apt:
        name: supervisor

    - name: "Derive broker address"
      shell: hostname | cut -d'.' -f2- | sed 's/wilab1/wall2/'
      register: server_hostname_suffix

    - set_fact:
        broker_hostname: "server.{{ server_hostname_suffix.stdout }}"

    - name: "Add opentestbed program to supervisor"
      become: True
      template:
        src: sensor-supervisord.conf.j2
        dest: /etc/supervisor/conf.d/otbox.conf

    - name: "Restart supervisor"
      become: True
      systemd:
        name: supervisor
        state: restarted

    - name: Add environment variables for OpenTestbed CLI
      blockinfile:
        path: ~/.profile
        block: |
          export OTB_TESTBED="wilab"
          export OTB_BROKER="{{ broker_hostname }}"